name: Build Windows Cleaner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build EXE
      shell: cmd
      run: |
        build.bat
        
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: WindowsCCleaner
        path: WindowsCCleaner.exe
        retention-days: 5
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          WindowsCCleaner.exe
          clean.bat
          README.md 